version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map React app to port 3000 on the host
    environment:
      REACT_APP_API_URL: "http://localhost:3000/"
    depends_on:
      - backend-service

  backend-service:
    image: news-app-news_app
    container_name: news-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    healthcheck:
      test: curl -f http://localhost:5000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5